version: "1.0"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: price_checker
      POSTGRES_USER: price_checker
      POSTGRES_PASSWORD: price_checker
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data