server.port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432:price_checker
    username: price_checker
    password: price_checker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
  liquibase:
    change-log: classpath:liquibase/changelog.yml
    url: jdbc:postgresql://localhost:5432:price_checker
    user: check_price
    password: check_price